# Generated by Django 5.0.6 on 2024-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_color_text_about_colors_about_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
