# Generated by Django 5.0.6 on 2024-07-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(default=list)),
                ('time', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
